language: ruby
before_install:
  - gem update --system
rvm:
  - 2.5.0
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - yarn lint
  - rspec
