# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9d523b86448bb4ce485845394321d017261e9b31c597af682878fceadd85bc165b7fce6e8ce7b3e74f8c3eef0fd81e6efdb46c4d27f0dc0deb7f04462c4aa5

test:
  secret_key_base: 07c3d910e73c73e812db61f644e3b6c120dad5a3263778dd3e489603a5beab15349a31940cfb6236be7a2c3054983aca063d3932efbbc3670aac56c0ed89af77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
